import streamlit as st
import whisper
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
import re
import os
import sqlite3
import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

# --- 1. DATABASE & PDF LOGIC ---
def init_db():
    conn = sqlite3.connect('meetings.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS meeting_history 
                 (id INTEGER PRIMARY KEY, date TEXT, title TEXT, summary TEXT, actions TEXT, transcript TEXT)''')
    conn.commit()
    conn.close()

def create_pdf(title, summary, actions, date):
    pdf_path = f"Meeting_Minutes_{date}.pdf"
    c = canvas.Canvas(pdf_path, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 750, "OFFICIAL MEETING MINUTES")
    c.setFont("Helvetica", 10)
    c.drawString(100, 735, f"Generated by Enterprise AI | {date}")
    
    c.line(100, 725, 500, 725)
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 700, f"TITLE: {title}")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 670, "EXECUTIVE SUMMARY")
    c.setFont("Helvetica", 10)
    text_obj = c.beginText(100, 650)
    text_obj.textLines(summary)
    c.drawText(text_obj)
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 500, "KEY ACTION ITEMS & DEADLINES")
    c.setFont("Helvetica", 10)
    y = 480
    for item in actions.split('\n'):
        if item.strip():
            c.drawString(110, y, f"- {item.strip()}")
            y -= 15
    c.save()
    return pdf_path

init_db()

# --- 2. UI & UX (Professional Theme) ---
st.set_page_config(page_title="Strategic Meeting Intelligence", layout="wide")

st.markdown("""
    <style>
    .stApp {
        background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url("https://images.unsplash.com/photo-1517245318773-b7b83ca927a0?q=80&w=2070");
        background-size: cover;
    }
    .glass-morphism {
        background: rgba(255, 255, 255, 0.9);
        padding: 25px; border-radius: 15px;
        box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.2);
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. MODEL LOADING ---
@st.cache_resource
def load_enterprise_models():
    w_model = whisper.load_model("base")
    tokenizer = AutoTokenizer.from_pretrained("sshleifer/distilbart-cnn-12-6")
    s_model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/distilbart-cnn-12-6")
    return w_model, tokenizer, s_model

w_model, tokenizer, s_model = load_enterprise_models()

# --- 4. NAVIGATION ---
menu = ["🎙️ New Meeting Analysis", "📅 Meeting History", "💬 AI Q&A Chatbot"]
choice = st.sidebar.selectbox("Workspace Menu", menu)

# --- TAB 1: ANALYSIS ---
if choice == "🎙️ New Meeting Analysis":
    st.markdown('<div class="glass-morphism">', unsafe_allow_html=True)
    st.title("💼 Strategy Room")
    
    audio_file = st.file_uploader("Upload Audio/Video", type=["mp3", "wav", "mp4", "m4a"])
    meeting_title = st.text_input("Meeting Subject", placeholder="e.g. Project Delivery Discussion")
    
    if audio_file and st.button("🚀 Process Intelligence"):
        with st.spinner("Analyzing audio context..."):
            # FIX: Temporary file handling
            with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splitext(audio_file.name)[1]) as tmp:
                tmp.write(audio_file.getvalue())
                tmp_path = tmp.name

            # A. Transcription
            result = w_model.transcribe(tmp_path)
            raw_text = result["text"]
            os.remove(tmp_path) # Cleanup

            # B. Advanced Extraction (Dates, Days, Actions)
            # Dhund raha hai: "will", "by Friday", "deadline", "Monday", etc.
            action_list = re.findall(r"([^.]*(?:will|need to|deadline|by|must|monday|tuesday|wednesday|thursday|friday|saturday|sunday)[^.]*\.)", raw_text, re.I)
            final_actions = "\n".join([a.strip() for a in action_list])

            # C. Professional Summary
            inputs = tokenizer("summarize: " + raw_text[:2000], return_tensors="pt", max_length=1024, truncation=True)
            summary_ids = s_model.generate(inputs["input_ids"], max_length=150, min_length=60, forced_bos_token_id=0)
            summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

            # D. Save to SQLite
            today = datetime.now().strftime("%d-%m-%Y %H:%M")
            conn = sqlite3.connect('meetings.db')
            c = conn.cursor()
            c.execute("INSERT INTO meeting_history (date, title, summary, actions, transcript) VALUES (?,?,?,?,?)",
                      (today, meeting_title, summary, final_actions, raw_text))
            conn.commit()
            conn.close()

            st.success("Analysis Complete!")
            
            # PDF Generation
            pdf_path = create_pdf(meeting_title, summary, final_actions, today)
            with open(pdf_path, "rb") as f:
                st.download_button("📥 Download Meeting Minutes (PDF)", f, file_name=f"{meeting_title}.pdf")
    st.markdown('</div>', unsafe_allow_html=True)

# --- TAB 2: HISTORY ---
elif choice == "📅 Meeting History":
    st.title("📅 Archives & Records")
    conn = sqlite3.connect('meetings.db')
    meetings = conn.execute("SELECT * FROM meeting_history ORDER BY id DESC").fetchall()
    
    for row in meetings:
        with st.expander(f"Record #{row[0]} | {row[1]} | {row[2]}"):
            col1, col2 = st.columns(2)
            with col1:
                edited_summary = st.text_area("Summary", row[3], height=200, key=f"s_{row[0]}")
            with col2:
                edited_actions = st.text_area("Deliverables", row[4], height=200, key=f"a_{row[0]}")
            
            if st.button("Save Changes", key=f"b_{row[0]}"):
                c = conn.cursor()
                c.execute("UPDATE meeting_history SET summary=?, actions=? WHERE id=?", (edited_summary, edited_actions, row[0]))
                conn.commit()
                st.toast("Record Updated!")
    conn.close()

# --- TAB 3: Q&A CHATBOT ---
elif choice == "💬 AI Q&A Chatbot":
    st.title("💬 Meeting Consultant")
    conn = sqlite3.connect('meetings.db')
    titles = {r[2]: r[5] for r in conn.execute("SELECT * FROM meeting_history").fetchall()}
    
    if titles:
        selected = st.selectbox("Select Meeting to Query", list(titles.keys()))
        user_query = st.text_input("Ask a question about this meeting...")
        
        if user_query:
            context = titles[selected]
            # Simple keyword search logic for the answer
            relevant_snippets = [s for s in context.split('.') if any(w.lower() in s.lower() for w in user_query.split())]
            if relevant_snippets:
                st.write("**AI Consultant:** " + ". ".join(relevant_snippets[:2]) + ".")
            else:
                st.write("**AI Consultant:** I couldn't find a specific mention of that in the transcript.")
    else:
        st.info("No meetings in history to chat about.")
