import streamlit as st
import whisper
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch
import re
import os
import sqlite3
import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

# --- 1. DATABASE LOGIC (History & Storage) ---
def init_db():
    conn = sqlite3.connect('meetings.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS meeting_history 
                 (id INTEGER PRIMARY KEY, date TEXT, title TEXT, summary TEXT, actions TEXT, transcript TEXT)''')
    conn.commit()
    conn.close()

def create_pdf(title, summary, actions, date):
    pdf_path = f"Meeting_Minutes_{date.replace(':', '-')}.pdf"
    c = canvas.Canvas(pdf_path, pagesize=letter)
    
    # PDF Header Design
    c.setFont("Helvetica-Bold", 18)
    c.drawString(100, 750, "OFFICIAL MEETING MINUTES")
    c.setFont("Helvetica", 10)
    c.drawString(100, 735, f"Date: {date} | Generated by AI Intelligence")
    c.line(100, 725, 500, 725)
    
    # Meeting Body
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 700, f"SUBJECT: {title.upper()}")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 670, "EXECUTIVE SUMMARY:")
    c.setFont("Helvetica", 10)
    y_pos = 650
    # Text wrapping for long summaries
    for line in [summary[i:i+85] for i in range(0, len(summary), 85)]:
        c.drawString(100, y_pos, line)
        y_pos -= 15
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, y_pos - 20, "KEY DELIVERABLES & DEADLINES:")
    y_pos -= 40
    for item in actions.split('\n'):
        if item.strip():
            c.drawString(110, y_pos, f"• {item.strip()}")
            y_pos -= 15
            
    c.save()
    return pdf_path

init_db()

# --- 2. PROFESSIONAL UI/UX ---
st.set_page_config(page_title="Strategic Meeting Intelligence", layout="wide")

st.markdown("""
    <style>
    .stApp {
        background: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), 
                    url("https://images.unsplash.com/photo-1431540015161-0bf868a2d407?q=80&w=2070");
        background-size: cover;
    }
    .glass-box {
        background: rgba(255, 255, 255, 0.92);
        padding: 2rem;
        border-radius: 15px;
        box-shadow: 0 10px 30px rgba(0,0,0,0.5);
        color: #1e293b;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. MODEL LOADING ---
@st.cache_resource
def load_models():
    w_model = whisper.load_model("base")
    tokenizer = AutoTokenizer.from_pretrained("sshleifer/distilbart-cnn-12-6")
    s_model = AutoModelForSeq2SeqLM.from_pretrained("sshleifer/distilbart-cnn-12-6")
    return w_model, tokenizer, s_model

w_model, tokenizer, s_model = load_models()

# --- 4. NAVIGATION & WORKSPACE ---
choice = st.sidebar.radio("Navigate Workspace", ["🎙️ New Analysis", "📅 Meeting Archives", "💬 Q&A Chatbot"])

# --- TAB 1: NEW ANALYSIS ---
if choice == "🎙️ New Analysis":
    st.markdown('<div class="glass-box">', unsafe_allow_html=True)
    st.title("🏛️ Strategic Analysis Room")
    
    audio_file = st.file_uploader("Upload Recording", type=["mp3", "wav", "mp4", "m4a"])
    meeting_title = st.text_input("Meeting Subject", placeholder="e.g. Weekly Project Sync")
    
    if audio_file and st.button("🚀 Synthesize Minutes"):
        with st.spinner("Decoding audio and identifying strategic intent..."):
            with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splitext(audio_file.name)[1]) as tmp:
                tmp.write(audio_file.getvalue())
                tmp_path = tmp.name

            # A. Transcription & Metadata Extraction
            result = w_model.transcribe(tmp_path)
            raw_text = result["text"]
            os.remove(tmp_path)

            # B. Smart Pattern Matching (Days, Dates, Keywords)
            # Dhoond raha hai: Monday-Sunday, dates, "will", "deadline", "by"
            patterns = r"([^.]*(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|will|must|deadline|by|due|completed)[^.]*\.)"
            action_items = "\n".join([a.strip() for a in re.findall(patterns, raw_text, re.I)])

            # C. Professional Summary
            inputs = tokenizer("summarize: " + raw_text[:2500], return_tensors="pt", max_length=1024, truncation=True)
            summary_ids = s_model.generate(inputs["input_ids"], max_length=150, min_length=60, forced_bos_token_id=0)
            summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

            # D. Database Entry
            today = datetime.now().strftime("%d-%m-%Y %H:%M")
            conn = sqlite3.connect('meetings.db')
            c = conn.cursor()
            c.execute("INSERT INTO meeting_history (date, title, summary, actions, transcript) VALUES (?,?,?,?,?)",
                      (today, meeting_title, summary, action_items, raw_text))
            conn.commit()
            conn.close()

            st.success("Analysis finalized and saved to history.")
            
            # PDF Generation
            pdf_path = create_pdf(meeting_title, summary, action_items, today)
            with open(pdf_path, "rb") as f:
                st.download_button("📥 Download Official PDF Minutes", f, file_name=f"{meeting_title}.pdf")
    st.markdown('</div>', unsafe_allow_html=True)

# --- TAB 2: ARCHIVES (History & Edit) ---
elif choice == "📅 Meeting Archives":
    st.title("📅 Intelligence Archives")
    conn = sqlite3.connect('meetings.db')
    meetings = conn.execute("SELECT * FROM meeting_history ORDER BY id DESC").fetchall()
    
    for row in meetings:
        with st.expander(f"Record: {row[2]} | Date: {row[1]}"):
            col1, col2 = st.columns(2)
            with col1:
                e_sum = st.text_area("Edit Summary", row[3], height=200, key=f"s{row[0]}")
            with col2:
                e_act = st.text_area("Edit Action Items", row[4], height=200, key=f"a{row[0]}")
            
            if st.button("Update Record", key=f"btn{row[0]}"):
                c = conn.cursor()
                c.execute("UPDATE meeting_history SET summary=?, actions=? WHERE id=?", (e_sum, e_act, row[0]))
                conn.commit()
                st.toast("Database updated!")
    conn.close()

# --- TAB 3: Q&A CHATBOT ---
elif choice == "💬 Q&A Chatbot":
    st.title("💬 Strategic Consultant")
    conn = sqlite3.connect('meetings.db')
    data = {r[2]: r[5] for r in conn.execute("SELECT * FROM meeting_history").fetchall()}
    
    if data:
        selected_m = st.selectbox("Select Meeting to Query", list(data.keys()))
        user_query = st.text_input("Ask a question (e.g., What was the deadline for Task 1?)")
        
        if user_query:
            context = data[selected_m]
            # Simple Semantic Keyword Search
            relevant = [s for s in context.split('.') if any(w.lower() in s.lower() for w in user_query.split())]
            if relevant:
                st.markdown(f"**AI Response:** {' '.join(relevant[:2])}.")
            else:
                st.write("AI is unable to find a specific mention. Try different keywords.")
    else:
        st.info("No meetings saved in archives.")
